name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    
    - uses: actions/setup-python@v4

    - name: Intall python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r data/requirements.txt
    
    - name: make
      run: make
    - name: make test
      run: make test
